services:
  redis:
    image: idc-aisi2223-redis

  webapp:
    image: idc-aisi2223-webcounter
    volumes:
        - type: bind
          source: src/
          target: /src
    ports:
        - "80:5000"
    #links:
    #    - "redis:redis-server"
    healthcheck:
        test: ["CMD", "curl", "--fail", "http://127.0.0.1:5000"]
        interval: 15s
    depends_on:
      - "redis"
