services:
  redis:
    image: localhost:5000/idc-aisi2223-redis

  webapp:
    image: localhost:5000/idc-aisi2223-webcounter
    volumes:
        - type: bind
          source: /vagrant/ej3/src
          target: /src
    ports:
        - "80:5000"
    healthcheck:
        test: ["CMD", "curl", "--fail", "http://127.0.0.1:5000"]
        interval: 15s
    depends_on:
      - "redis"     
    deploy:
      mode: replicated
      replicas: 3
